language: java
jdk:
  - oraclejdk8
  
install: mvn install -U -DskipTests=true
script:
  mvn integration-test verify -Ptest
env:
  environment=test
deploy:
  provider: heroku
  api_key:
    secure: "788442021d5a77c91b8cca89db466f9e491d1d9b" # API Key, encontrado em Account Settings
  on: master # Configuração de branch
  app: secure-escarpment-22257 # Nome da app no Heroku
